---
- hosts: all
  become: true
  tasks:
    - debug:
        msg: "demarrage {{ PWD }}"
    - name: current_working_directory
      shell: pwd
      register: current_working_directory
    - name: load
      include_vars:
        file: "{{ PWD }}/prod.properties"
    - debug:
        msg: "{{ inventory_hostname }} and {{ ids }}"
    - name: build config file from template
      vars:
          host_id: "{{ ids[inventory_hostname].value }}"
      template:
        src: ../config/config.yaml.template
        dest: ~{{ user_to_create }}/config/config.yaml
        owner: "{{ user_to_create }}"
        mode: 0666
    - name: build bin file from template
      template:
        src: ../bin/run.sh.template
        dest: ~{{ user_to_create }}/bin/run.sh
        owner: "{{ user_to_create }}"
        mode: 0744
    - name: build bin file from template
      template:
        src: ../config/log4j.xml.template
        dest: ~{{ user_to_create }}/config/log4j.xml
        owner: "{{ user_to_create }}"
        mode: 0744
    - name: build client_jaas file from template
      template:
        src: ../config/client_jaas.conf.template
        dest: ~{{ user_to_create }}/config/client_jaas.conf
        owner: "{{ user_to_create }}"
        mode: 0644
    - name: Deploy key tab file
      copy:
        src: ../../WorkFlow/ansible/tools/application/keytabs/{{ user_to_create }}.keytab
        dest: ~{{ user_to_create }}/config/{{ user_to_create }}.keytab
        owner: "{{ user_to_create }}"
        mode: 0600
    - name: Copy jars
      copy:
        src: "{{ PWD }}/../target/{{ jar_name }}"
        dest: ~{{ user_to_create }}/lib
      when:  inventory_hostname == "192.168.1.200"
  vars:
    ansible_become_pass: granada01
    PWD: "{{ lookup('env', 'PWD') }}"
    ids:
      192.168.1.200:
        value: 1
      192.168.1.201:
        value: 2
      192.168.1.202:
        value: 3
      192.168.1.203:
        value: 4
      192.168.1.205:
        value: 5
      192.168.1.206:
        value: 6
  