---
- hosts: all
  become: true
  tasks:
    - debug:
        msg: "Start process {{ PWD }}"

    - name: Stop appli
      shell: systemctl stop {{item}}_appli.service
      loop:
        - wf_archive
        - wf_cmp_hashkey
        - wf_dupcheck
        - wf_ext_img_infos
        - wf_hbase
        - wf_proc_and_publish_exif_data
        - wf_proc_and_publish_photo
        - wf_scan
        - wf_copy_files
        
    - name: Start hbase
      shell: systemctl start {{item}}_appli.service
      loop:
        - wf_hbase
      when: inventory_hostname == "192.168.1.206" or inventory_hostname == "192.168.1.203" or inventory_hostname  == "192.168.1.201"
        
    - name: Start appli
      shell: systemctl start {{item}}_appli.service
      loop:
        - wf_archive
        - wf_copy_files
        - wf_cmp_hashkey
        - wf_dupcheck
        - wf_ext_img_infos
        - wf_hbase
        - wf_proc_and_publish_exif_data
        - wf_proc_and_publish_photo
        - wf_scan
        - wf_copy_files
  vars:
    ansible_become_pass: granada01
    PWD: "{{ lookup('env', 'PWD') }}"
